# -*- coding: utf-8 -*-
"""proyek_machine_learning_terapan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tqRrzvZjC9tUegn-YkE_JdqtydezopWU

# Import Library
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from imblearn.over_sampling import SMOTE
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.model_selection import RandomizedSearchCV, GridSearchCV

"""# Data Load"""

df = pd.read_csv('dataset\heart.csv')
df

"""# Data Understanding"""

df.info()

df.describe()

df.isnull().sum()

df.duplicated().sum()

df.drop_duplicates(inplace=True)
df.info()

"""### Add Data"""

df2 = pd.read_csv('dataset\heart_statlog_cleveland_hungary_final.csv')
df2

df2.info()

df2.duplicated().sum()

df2.drop_duplicates(inplace=True)
df2.info()

"""rename df2"""

df2 = df2.rename(columns={
    'chest pain type': 'cp',
    'resting bp s': 'trestbps',
    'cholesterol': 'chol',
    'fasting blood sugar': 'fbs',
    'resting ecg': 'restecg',
    'max heart rate': 'thalach',
    'exercise angina': 'exang',
    'ST slope': 'slope'
})
df2.info()

df2.describe()

common_columns = ['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs',
                  'restecg', 'thalach', 'exang', 'oldpeak', 'slope', 'target']

df_filtered = df[common_columns]
df2_filtered = df2[common_columns]

df_combined = pd.concat([df_filtered, df2_filtered], ignore_index=True)
df_combined.info()

"""gabungkan data dengan fitur yg terdapat pada df2

## Exploratory Data Analysis

### Distribusi fitur
"""

df_combined.hist(figsize=(12, 10), bins=20)
plt.tight_layout()
plt.show()

"""Gambar di atas menunjukkan distribusi dari setiap fitur dalam dataset heart.csv. Tujuan visualisasi ini adalah untuk memahami karakteristik data dan melihat pola atau anomali sebelum dilakukan proses modeling lebih lanjut.

Berikut beberapa insight penting dari histogram tiap fitur:

- age: Usia pasien berkisar antara 30 hingga 77 tahun, dengan mayoritas berada di rentang 50–60 tahun.

- sex: Sebagian besar pasien adalah laki-laki (1), menunjukkan ketimpangan distribusi gender dalam dataset.

- cp (chest pain type): Kategori 0 dan 4 mendominasi tipe nyeri dada, menunjukkan dua tipe tersebut paling umum.

- trestbps (resting blood pressure): Sebagian besar tekanan darah istirahat berada di antara 110–140 mmHg.

- chol (cholesterol): Kadar kolesterol memiliki distribusi miring ke kanan (right-skewed), dengan sebagian besar pasien memiliki kadar antara 200–300 mg/dL.

- fbs (fasting blood sugar > 120 mg/dL): Mayoritas pasien memiliki kadar gula darah puasa normal (0).

- restecg (resting ECG results): Kategori 0 mendominasi, menunjukkan hasil EKG yang normal lebih sering terjadi.

- thalach (maximum heart rate achieved): Detak jantung maksimum bervariasi, namun paling sering berada di rentang 130–170 bpm.

- exang (exercise-induced angina): Sebagian besar pasien tidak mengalami nyeri dada akibat olahraga.

- oldpeak (ST depression): Mayoritas pasien memiliki nilai oldpeak mendekati 0, meskipun ada outlier hingga nilai 6.

- slope (slope of the ST segment): Kategori 1 (kemiringan rata-rata) paling umum, disusul kategori 2 dan 0.

- target: Label target menunjukkan bahwa data relatif seimbang, dengan sedikit lebih banyak pasien yang terdiagnosis penyakit jantung (1) dibandingkan yang tidak (0).

### Target analysis
"""

sns.countplot(x='target', data=df_combined)

df_combined['target'].value_counts(normalize=True)

"""Fitur target menunjukkan kondisi jantung pasien, dengan nilai 1 berarti memiliki penyakit jantung dan 0 berarti tidak.

Distribusi data:

- 1 (sakit): 55,1%

- 0 (tidak sakit): 44,9%

### Relasi antar fitur
"""

plt.figure(figsize=(16, 12))

# 1. Chest Pain Type vs Target
plt.subplot(3, 2, 1)
sns.countplot(x='cp', hue='target', data=df_combined)
plt.title('Chest Pain Type vs Target')

plt.tight_layout()
plt.show()

"""Grafik menunjukkan distribusi jenis nyeri dada (cp) terhadap kondisi jantung (target):

- cp = 4 (asymptomatic) paling sering dikaitkan dengan pasien yang memiliki penyakit jantung (target = 1).

- cp = 2 dan 3 cenderung lebih umum pada pasien tanpa penyakit jantung (target = 0).

- Pasien dengan cp = 1 lebih banyak memiliki penyakit jantung dibanding yang tidak.

Kesimpulan: Jenis nyeri dada memiliki korelasi kuat terhadap kondisi jantung, khususnya cp = 4 sebagai indikator signifikan penyakit jantung.
"""

# 2. Sex vs Target
plt.figure(figsize=(16, 12))
plt.subplot(3, 2, 2)
sns.countplot(x='sex', hue='target', data=df_combined)
plt.title('Sex vs Target')

plt.tight_layout()
plt.show()

"""- sex = 1 (laki-laki) memiliki jumlah kasus penyakit jantung (target = 1) yang lebih tinggi dibanding yang tidak sakit.

- sex = 0 (perempuan) justru lebih banyak yang tidak menderita penyakit jantung.

Kesimpulan: Laki-laki cenderung memiliki risiko lebih tinggi terhadap penyakit jantung dibanding perempuan dalam dataset ini.
"""

# 3. Fasting Blood Sugar vs Target
plt.figure(figsize=(16, 12))
plt.subplot(3, 2, 3)
sns.countplot(x='fbs', hue='target', data=df_combined)
plt.title('Fasting Blood Sugar > 120 mg/dl vs Target')

plt.tight_layout()
plt.show()

"""- Pada fbs = 0 (gula darah ≤ 120 mg/dl), distribusi antara penderita dan non-penderita penyakit jantung hampir seimbang.

- Pada fbs = 1 (gula darah > 120 mg/dl), mayoritas mengalami penyakit jantung (target = 1).

Kesimpulan: Gula darah puasa tinggi berpotensi berkorelasi dengan peningkatan risiko penyakit jantung, meskipun jumlah kasusnya relatif kecil.
"""

# 4. Resting ECG vs Target
plt.figure(figsize=(16, 12))
plt.subplot(3, 2, 4)
sns.countplot(x='restecg', hue='target', data=df_combined)
plt.title('Resting ECG vs Target')

plt.tight_layout()
plt.show()

"""- Pada restecg = 0 (hasil normal), jumlah penderita dan non-penderita hampir seimbang.

- Pada restecg = 1 (abnormalitas ST-T), lebih banyak yang menderita penyakit jantung.

- Pada restecg = 2 (hipertrofi ventrikel kiri), penderita juga sedikit lebih banyak.

Kesimpulan: Abnormalitas hasil ECG, terutama kategori 1 dan 2, cenderung terkait dengan peningkatan risiko penyakit jantung.
"""

# 5. Exercise-Induced Angina vs Target
plt.figure(figsize=(16, 12))
plt.subplot(3, 2, 5)
sns.countplot(x='exang', hue='target', data=df_combined)
plt.title('Exercise-Induced Angina vs Target')

plt.tight_layout()
plt.show()

"""- Pada exang = 0 (tidak mengalami angina saat olahraga), jumlah penderita dan non-penderita cukup seimbang.

- Pada exang = 1 (mengalami angina saat olahraga), mayoritas adalah penderita penyakit jantung.

Kesimpulan: Angina yang dipicu oleh aktivitas fisik berkorelasi kuat dengan penyakit jantung.
"""

# 6. ST Slope vs Target
plt.figure(figsize=(16, 12))
plt.subplot(3, 2, 6)
sns.countplot(x='slope', hue='target', data=df_combined)
plt.title('ST Slope vs Target')

plt.tight_layout()
plt.show()

"""# Data Preparation"""

df.drop_duplicates(inplace=True)
df.info()

"""Karena jumlah data hanya 302 entri, yang relatif kecil untuk proses pelatihan model machine learning, maka dilakukan pencarian dan penambahan data tambahan dari sumber lain agar analisis dan model prediksi menjadi lebih kuat dan representatif.

### Cleaning Data
"""

df_combined.duplicated().sum()

df_combined.drop_duplicates(inplace=True)
df_combined.info()

df_combined.describe()

Q1 = df_combined[['oldpeak', 'chol', 'trestbps']].quantile(0.25)
Q3 = df_combined[['oldpeak', 'chol', 'trestbps']].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

df_combined = df_combined[
    (df_combined['chol'] >= lower_bound['chol']) & (df_combined['chol'] <= upper_bound['chol']) &
    (df_combined['oldpeak'] >= lower_bound['oldpeak']) & (df_combined['oldpeak'] <= upper_bound['oldpeak']) &
    (df_combined['trestbps'] >= lower_bound['trestbps']) & (df_combined['trestbps'] <= upper_bound['trestbps'])
]

df_combined.describe()

df_combined.info()

"""dataset yang digunakan adalah heart.csv dan heart_statlog_cleveland_hungary_final.csv dengan total 989 entri dan 11 kolom fitur medis. Data ini diadaptasi dari dataset publik dari Kaggle.

- age: usia pasien

- sex: jenis kelamin (1 = laki-laki, 0 = perempuan)

- cp: jenis nyeri dada (0–4)

- trestbps: tekanan darah saat istirahat (mm Hg)

- chol: kadar kolesterol (mg/dl)

- fbs: gula darah puasa > 120 mg/dl (1 = ya, 0 = tidak)

- restecg: hasil EKG saat istirahat

- thalach: detak jantung maksimum

- exang: nyeri dada akibat latihan (1 = ya)

- oldpeak: depresi ST (numerik)

- slope: kemiringan segmen ST (0–3)

- target: diagnosis akhir (0 = tidak sakit, 1 = ada penyakit jantung)

## Split Dataset
"""

X = df_combined.drop('target', axis=1)
y = df_combined['target']

# Split data into 80% train, 10% validation, and 10% test
X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.333, random_state=42, stratify=y_temp)

print("X_train shape:", X_train.shape)
print("X_val shape:", X_val.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_val shape:", y_val.shape)
print("y_test shape:", y_test.shape)

"""Pada tahap ini, saya melakukan pembagian dataset menjadi tiga bagian utama yaitu data latih (training), data validasi (validation), dan data uji (testing). Proses ini dilakukan untuk mempersiapkan data sebelum digunakan dalam pelatihan dan evaluasi model machine learning.

Hasil split data menunjukkan bahwa:

- Data latih (X_train) berjumlah 791 sampel dengan 11 fitur, digunakan untuk melatih model agar dapat mempelajari pola dari data.

- Data validasi (X_val) berjumlah 132 sampel, digunakan untuk menguji performa model selama pelatihan dan membantu melakukan tuning parameter agar model tidak overfitting.

- Data uji (X_test) berjumlah 66 sampel, berfungsi sebagai data baru yang tidak terlihat oleh model selama pelatihan, untuk mengevaluasi performa akhir model secara objektif.

- Target variabel (y) juga dibagi sesuai proporsi tersebut.

Tahapan pembagian dataset ini sangat penting untuk memastikan model yang dibangun dapat generalisasi dengan baik terhadap data yang belum pernah dilihat sebelumnya. Dengan adanya data validasi dan testing yang terpisah, proses pelatihan model menjadi lebih terkontrol dan hasil evaluasi model dapat dipercaya sebagai representasi performa nyata saat diaplikasikan ke data sesungguhnya.

## SMOTE data (hanya pada Train)
"""

smote = SMOTE(random_state=42)


X_train, y_train = smote.fit_resample(X, y)

print(f"Length of X_train after SMOTE: {len(X_train)}")
print(f"Length of y_train after SMOTE: {len(y_train)}")

"""Pada tahap ini, saya melakukan proses penyeimbangan data menggunakan metode SMOTE (Synthetic Minority Over-sampling Technique) untuk mengatasi ketidakseimbangan kelas pada dataset. Setelah penerapan SMOTE, dataset yang digunakan memiliki total 1.002 entri dengan 12 fitur, yang meliputi variabel numerik seperti usia (age), tekanan darah istirahat (trestbps), kolesterol (chol), dan fitur target (target).

Dari output informasi struktur data, terlihat bahwa semua kolom memiliki nilai yang lengkap tanpa missing value (non-null count = 1.002 pada setiap kolom). Dataset terdiri dari 11 fitur numerik bertipe integer dan 1 fitur bertipe float (oldpeak). Ukuran memori yang digunakan dataset ini sebesar sekitar 126 KB.

Dengan data yang sudah seimbang ini, model machine learning nantinya dapat dilatih tanpa bias terhadap kelas mayoritas, sehingga diharapkan hasil prediksi menjadi lebih akurat dan fair.

## Feature Scaling
"""

scaler = StandardScaler()

# salin data supaya tidak mengubah asli
X_train_scaled = X_train.copy()
X_val_scaled = X_val.copy()
X_test_scaled = X_test.copy()

# scaling hanya beberapa fitur
fitur_scaling = ['age', 'trestbps', 'chol', 'thalach', 'oldpeak']

X_train_scaled[fitur_scaling] = scaler.fit_transform(X_train[fitur_scaling])
X_val_scaled[fitur_scaling] = scaler.transform(X_val[fitur_scaling])
X_test_scaled[fitur_scaling] = scaler.transform(X_test[fitur_scaling])

"""Pada tahap ini, dilakukan proses scaling menggunakan StandardScaler untuk menormalkan beberapa fitur numerik terpilih yakni usia (age), tekanan darah (trestbps), kolesterol (chol), detak jantung maksimum (thalach), dan perubahan ST (oldpeak). Scaling hanya diterapkan pada fitur-fitur tersebut karena memiliki rentang nilai yang berbeda jauh dibanding fitur kategori lainnya.

Proses ini penting agar setiap fitur memiliki skala yang seragam dengan rata-rata nol dan standar deviasi satu, sehingga model machine learning dapat belajar lebih efektif tanpa bias akibat perbedaan skala fitur. Scaling juga membantu mempercepat konvergensi algoritma dan meningkatkan performa model.

# Modeling

## Model 1 Random Forest
"""

param_rf = {
    'n_estimators': [100, 200, 300],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

rf_model = RandomForestClassifier(random_state=42)
random_search_rf = RandomizedSearchCV(estimator=rf_model, param_distributions=param_rf, n_iter=60, cv=5, scoring='accuracy', random_state=42, verbose=1)
random_search_rf.fit(X_train_scaled, y_train)

best_params_rf = random_search_rf.best_params_
best_rf_model = random_search_rf.best_estimator_

y_pred_rf = best_rf_model.predict(X_val_scaled)

print("=====Result=====")
print("Accuracy : ", accuracy_score(y_val,y_pred_rf))
print("====Classification Report====")
target_names = ['Tidak Sakit Jantung', 'Sakit Jantung']
print(classification_report(y_val,y_pred_rf, target_names=target_names))
print("====Conf Matrix====")
print(confusion_matrix(y_val, y_pred_rf,))
print("====Parameters Used====")
print(best_params_rf)

"""Model yang diuji menggunakan 5-fold cross-validation dengan 60 kombinasi hyperparameter menghasilkan akurasi sebesar 80,4%. Dari classification report, model mampu mengklasifikasikan kelas "Tidak Sakit Jantung" dengan precision 78% dan recall 86%, serta kelas "Sakit Jantung" dengan precision 84% dan recall 75%. Nilai f1-score untuk kedua kelas berada di kisaran 0,79–0,81, menunjukkan performa yang seimbang.

Confusion matrix memperlihatkan bahwa model melakukan 13 kesalahan prediksi pada kelas negatif dan 22 kesalahan pada kelas positif. Hyperparameter terbaik yang diperoleh adalah n_estimators=100, min_samples_split=2, dan min_samples_leaf=4, tanpa batasan kedalaman pohon (max_depth=None).

Proses improvement dilakukan dengan melakukan hyperparameter tuning untuk menemukan kombinasi parameter yang optimal, meningkatkan performa model dibanding pengaturan default. Jika menggunakan beberapa algoritma, model ini dipilih sebagai solusi terbaik karena memberikan keseimbangan antara akurasi, precision, dan recall yang baik, serta stabilitas hasil pada validasi silang.

## Model 2 XGBoost
"""

param_xgb = {
    'n_estimators': [100, 200, 300, 400],
    'max_depth': [7, 8, 9, 10, 15],
    'learning_rate': [0.01, 0.1, 0.2],
    'subsample': [0.8, 0.9, 1.0],
    'colsample_bytree': [0.8, 0.9, 1.0]
}

xgb_model = XGBClassifier(random_state=42)
random_search_xgb = RandomizedSearchCV(estimator=xgb_model, param_distributions=param_xgb, n_iter=20, cv=5, scoring='accuracy', random_state=42, verbose=1)
random_search_xgb.fit(X_train_scaled, y_train)

best_params_xgb = random_search_xgb.best_params_
best_xgb_model = random_search_xgb.best_estimator_

y_pred_xgb = best_xgb_model.predict(X_val_scaled)

print("=====Result=====")
print("Accuracy : ", accuracy_score(y_val,y_pred_xgb))
print("====Classification Report====")
target_names = ['Tidak Sakit Jantung', 'Sakit Jantung']
print(classification_report(y_val, y_pred_xgb, target_names=target_names))
print("====Conf Matrix====")
print(confusion_matrix(y_val, y_pred_xgb))
print("====Parameters Used====")
print(best_params_xgb)

"""Model XGBoost diuji menggunakan 5-fold cross-validation dengan 20 kombinasi hyperparameter, menghasilkan akurasi sebesar 81,0%. Dari classification report, model menunjukkan precision dan recall yang seimbang untuk kelas "Tidak Sakit Jantung" (precision 79%, recall 84%) dan "Sakit Jantung" (precision 83%, recall 78%). F1-score rata-rata sekitar 0,81, menunjukkan performa yang solid di kedua kelas.

Confusion matrix memperlihatkan 14 kesalahan prediksi pada kelas negatif dan 20 pada kelas positif. Hyperparameter terbaik yang diperoleh adalah n_estimators=300, max_depth=7, learning_rate=0.01, subsample=0.8, dan colsample_bytree=0.8, yang membantu mengontrol overfitting dan meningkatkan generalisasi model.

Model ini menunjukkan performa sedikit lebih baik dibanding model sebelumnya dan menjadi kandidat kuat sebagai solusi utama.

# Evaluation

## Model 1 Evaluation
"""

y_test_rf = best_rf_model.predict(X_test_scaled)

print("=====Result Random Forest=====")
print("Accuracy : ", accuracy_score(y_test,y_test_rf))
print("====Classification Report====")
target_names = ['Tidak Sakit Jantung', 'Sakit Jantung']
print(classification_report(y_test, y_test_rf, target_names=target_names))
print("====Conf Matrix====")
print(confusion_matrix(y_test, y_test_rf))

importances = best_rf_model.feature_importances_

# Buat DataFrame untuk visualisasi
feature_names = X_train.columns
feat_importances = pd.Series(importances, index=feature_names)

# Urutkan dari penting ke tidak
feat_importances = feat_importances.sort_values(ascending=False)

# Visualisasi bar chart
plt.figure(figsize=(10,6))
feat_importances.plot(kind='bar')
plt.title('Feature Importance - Random Forest')
plt.ylabel('Importance Score')
plt.tight_layout()
plt.show()

"""Model Random Forest mencapai akurasi 95,4% dengan precision, recall, dan F1-score yang seimbang, menunjukkan kemampuan deteksi penyakit jantung yang sangat baik. Kelas Sakit Jantung terdeteksi sempurna (recall 100%) dengan sedikit kesalahan (3 kasus) pada kelas Tidak Sakit Jantung, dari total 66 sampel. Evaluasi ini menunjukkan model mampu meminimalisir false negative, yang penting dalam konteks medis.

## Model 2 Evaluation
"""

y_test_xgb = best_xgb_model.predict(X_test_scaled)

print("=====Result XGBoost=====")
print("Accuracy : ", accuracy_score(y_test,y_test_xgb))
print("====Classification Report====")
target_names = ['Tidak Sakit Jantung', 'Sakit Jantung']
print(classification_report(y_test, y_test_xgb, target_names=target_names))
print("====Conf Matrix====")
print(confusion_matrix(y_test, y_test_xgb))

importances = best_xgb_model.feature_importances_

# Buat DataFrame untuk visualisasi
feature_names = X_train.columns
feat_importances = pd.Series(importances, index=feature_names)

# Urutkan dari penting ke tidak
feat_importances = feat_importances.sort_values(ascending=False)

# Visualisasi bar chart
plt.figure(figsize=(10,6))
feat_importances.plot(kind='bar')
plt.title('Feature Importance - XGBoost')
plt.ylabel('Importance Score')
plt.tight_layout()
plt.show()

"""Model XGBoost berhasil mencapai akurasi 96,9% pada data uji. Precision untuk kelas Tidak Sakit Jantung adalah 100% dan untuk Sakit Jantung sebesar 94%, sementara recall masing-masing 94% dan 100%. F1-score untuk kedua kelas adalah 0,97, menunjukkan performa yang sangat seimbang dan andal. Confusion matrix mencatat hanya 2 kesalahan pada kelas negatif, tanpa kesalahan pada kelas positif, dari total 66 sampel.

Dalam proyek ini, dua model dikembangkan: XGBoost dan Random Forest, dengan tuning khusus dilakukan pada Random Forest. Meskipun keduanya menunjukkan performa baik, XGBoost dipilih sebagai model akhir karena memberikan akurasi tertinggi, kemampuan deteksi sempurna pada kasus penyakit jantung, serta minim kesalahan diagnosis.

Visualisasi feature importance XGBoost (gambar di bawah) menunjukkan bahwa slope (kemiringan segmen ST) merupakan faktor paling dominan, diikuti oleh cp (tipe nyeri dada) dan exang (angina akibat olahraga):
"""