# -*- coding: utf-8 -*-
"""proyek_machine_learning_terapan2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14C3lCN7RdU_vQ1-DISOQy8fnQni7uDQO
"""

# from google.colab import drive
# drive.mount('/content/drive')

"""# Import Library"""

pip install sastrawi Tensorflow

import pandas as pd
import random
import numpy as np
import re
import string
import nltk
import random
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint, ReduceLROnPlateau
from sklearn.metrics.pairwise import cosine_similarity
from scipy.sparse import csr_matrix, hstack
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from imblearn.over_sampling import SMOTE
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.model_selection import RandomizedSearchCV
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from sklearn.feature_extraction.text import TfidfVectorizer
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('punkt_tab')

"""# Data Load"""

books_df = pd.read_csv('dataset\\Books.csv')
ratings_df = pd.read_csv('dataset\\Ratings.csv')
users_df = pd.read_csv('dataset\\Users.csv')

"""# Data Understanding"""

books_df.head()

books_df.isna().sum()

books_df.duplicated().sum()

books_df.info()

ratings_df.head()

ratings_df.isna().sum()

ratings_df.duplicated().sum()

ratings_df.info()

users_df.head()

users_df.isna().sum()

users_df.duplicated().sum()

users_df.info()

"""Dataset yang digunakan berasal dari Kaggle dan terdiri dari tiga file utama: **Books.csv**, **Ratings.csv**, dan **Users.csv**. Ketiga dataset ini merepresentasikan sistem rekomendasi buku berdasarkan informasi buku, pengguna, dan penilaian mereka terhadap buku.

<h5> 1. Books.csv <br>
Dataset ini memuat informasi tentang buku yang tersedia dalam sistem. Dataset ini terdiri dari 8 kolom dan 121.164 baris data. Terdapat 6 baris data kosong, namun tidak ditemukan data duplikat.

**Fitur-fitur:**
- `ISBN`: Nomor identifikasi unik untuk setiap buku (International Standard Book Number).
- `Book-Title`: Judul buku.
- `Book-Author`: Nama penulis buku.
- `Year-Of-Publication`: Tahun terbit buku.
- `Publisher`: Nama penerbit buku.
- `Image-URL-S`: URL gambar sampul buku ukuran kecil.
- `Image-URL-M`: URL gambar sampul buku ukuran sedang.
- `Image-URL-L`: URL gambar sampul buku ukuran besar.

---

<h5> 2. Ratings.csv <br>
Dataset ini mencatat penilaian (rating) yang diberikan oleh pengguna terhadap buku. Dataset ini terdiri dari 3 kolom dan 1.149.780 baris data. Tidak terdapat nilai kosong maupun data duplikat.

**Fitur-fitur:**
- `User-ID`: Identitas unik pengguna.
- `ISBN`: Identitas unik buku yang dinilai.
- `Book-Rating`: Nilai rating yang diberikan oleh pengguna terhadap buku.

---

<h5> 3. Users.csv <br>
Dataset ini menyimpan informasi tentang pengguna. Terdiri dari 3 kolom dan 278.858 baris data. Terdapat 110.762 nilai kosong, khususnya pada kolom 'Age', namun tidak ditemukan data duplikat.

**Fitur-fitur:**
- `User-ID`: Identitas unik pengguna.
- `Location`: Lokasi geografis pengguna dalam format “Kota, Negara Bagian, Negara”.
- `Age`: Usia pengguna.

## Univariate Exploratory Data Analysis

### Books Variabel
"""

books_df.info()

unique_isbn = books_df['ISBN'].unique()
print(f"Jumlah ISBN unik: {len(unique_isbn)}")

print("Contoh Judul Buku:", books_df['Book-Title'].unique()[:100])

print("Jumlah Penulis Unik:", books_df['Book-Author'].nunique())

# Convert 'Year-Of-Publication' to numeric, coercing errors to NaN
books_df['Year-Of-Publication'] = pd.to_numeric(books_df['Year-Of-Publication'], errors='coerce')

# Drop rows where 'Year-Of-Publication' is NaN after coercion
books_df.dropna(subset=['Year-Of-Publication'], inplace=True)

# Convert the column to integer type after removing NaNs
books_df['Year-Of-Publication'] = books_df['Year-Of-Publication'].astype(int)

print("Tahun Publikasi Unik:", books_df['Year-Of-Publication'].unique())
print("Range Tahun Publikasi:",
      books_df['Year-Of-Publication'].min(),
      "-",
      books_df['Year-Of-Publication'].max())

print("Jumlah Penerbit Unik:", books_df['Publisher'].nunique())
for col in ['Image-URL-S', 'Image-URL-M', 'Image-URL-L']:
    null_count = books_df[col].isnull().sum()
    unique_urls = books_df[col].nunique()
    print(f"{col}: {unique_urls} URL unik, {null_count} data kosong")

"""### Ratings Variabel"""

ratings_df.info()

unique_users = ratings_df['User-ID'].nunique()
print(f"Jumlah User unik: {unique_users}")

unique_isbn = ratings_df['ISBN'].nunique()
print(f"Jumlah ISBN unik: {unique_isbn}")

print("Nilai rating unik:", ratings_df['Book-Rating'].unique())
print("Jumlah nilai rating unik:", ratings_df['Book-Rating'].nunique())

# Jika ingin melihat distribusi rating
print("Distribusi rating buku:")
print(ratings_df['Book-Rating'].value_counts().sort_index())

"""### Users Variabel"""

users_df.info()

unique_users = users_df['User-ID'].nunique()
print(f"Jumlah User unik: {unique_users}")

unique_locations = users_df['Location'].nunique()
print(f"Jumlah lokasi unik: {unique_locations}")
print("Contoh lokasi:")
print(users_df['Location'].value_counts().head(5))

print(f"Jumlah data usia valid (tidak kosong): {users_df['Age'].notnull().sum()}")
print("Usia unik:", users_df['Age'].nunique())

# Usia yang tidak masuk akal (<5 atau >100)
invalid_ages = users_df[(users_df['Age'] < 5) | (users_df['Age'] > 100)]
print(f"Jumlah data usia tidak masuk akal: {invalid_ages.shape[0]}")

"""# Data Preprocessing"""

book_recom_df = pd.merge(books_df, ratings_df, on='ISBN')
book_recom_df = pd.merge(book_recom_df, users_df, on='User-ID')
book_recom_df.info()

book_recom_df.isna().sum()

book_recom_df.duplicated().sum()

"""## Data Cleaning"""

book_recom_df.dropna(inplace=True)
book_recom_df.info()

book_recom_df.drop('Image-URL-S', axis=1, inplace=True)
book_recom_df.drop('Image-URL-M', axis=1, inplace=True)
book_recom_df.drop('Image-URL-L', axis=1, inplace=True)
book_recom_df.drop('Publisher', axis=1, inplace=True)
book_recom_df.info()

#Hapus data dari ISBN yang meiliki huruf
book_recom_df = book_recom_df[book_recom_df['ISBN'].str.match('^\d+$', na=False)]

book_recom_df = book_recom_df.astype({
    'Year-Of-Publication': 'int64',
    'Age': 'int64',
    'ISBN' : 'int64'
})

book_recom_df.describe(include='all')

book_recom_df = book_recom_df[book_recom_df['Book-Rating'] > 0]
book_recom_df.describe(include='all')

print(np.sort(book_recom_df['Age'].unique()))

"""Menurut PBB, UHH (umur harapan hidup) dunia tahun 2024 ini mencapai 73,33 tahun, dengan UHH laki-laki sebesar 70,7 tahun dan perempuan mencapai 76,0 tahun. Oleh sebab itu saya akan mengambil batas usia di 75 tahun.

Sumber : https://www.kompas.id/artikel/sampai-usia-berapa-manusia-bisa-hidup

Menurut American Academy of Pediatrics (AAP), usia yang ideal bagi anak untuk belajar membaca saat berumur 6 tahun.

Sumber : https://www.tempo.co/gaya-hidup/umur-berapa-sebaiknya-anak-dibimbing-belajar-membaca--224080

"""

book_recom_df = book_recom_df[(book_recom_df['Age'] > 5) & (book_recom_df['Age'] < 76)]
book_recom_df.describe(include='all')

print(np.sort(book_recom_df['Year-Of-Publication'].unique()))

book_recom_df = book_recom_df[(book_recom_df['Year-Of-Publication'] > 0) & (book_recom_df['Year-Of-Publication'] < 2026)]
book_recom_df.describe(include='all')

# Pisahkan kolom Location menjadi 3 kolom: City, State, Country
book_recom_df[['City', 'State', 'Country']] = book_recom_df['Location'].str.split(',', n=2, expand=True)

# Hilangkan spasi di awal/akhir jika ada
book_recom_df['City'] = book_recom_df['City'].str.strip()
book_recom_df['State'] = book_recom_df['State'].str.strip()
book_recom_df['Country'] = book_recom_df['Country'].str.strip()
book_recom_df.describe(include='all')

print(np.sort(book_recom_df['ISBN'].unique()))

np.sort(book_recom_df['Book-Author'].unique())

# Remove author named 'x x'
book_recom_df = book_recom_df[book_recom_df['Book-Author'] != 'x x']

# Filter authors that appear only once
author_counts = book_recom_df['Book-Author'].value_counts()
authors_to_keep = author_counts[author_counts > 1].index
book_recom_df = book_recom_df[book_recom_df['Book-Author'].isin(authors_to_keep)]

# Display the unique authors after filtering
print(np.sort(book_recom_df['Book-Author'].unique()))
book_recom_df.describe(include='all')

# Hapus data dari ISBN yang memiliki kurang dari 10 digit setelah dikonversi ke string
book_recom_df = book_recom_df[book_recom_df['ISBN'].astype(str).str.len() >= 10]
print(np.sort(book_recom_df['ISBN'].unique()))

book_recom_df.info()

book_recom_df.describe(include='all')

book_recom_df.duplicated().sum()

book_recom_df = book_recom_df.drop_duplicates()
book_recom_df.duplicated().sum()

"""## Text Cleaning"""

def cleaningText (text):
  text = re.sub(r'@[A-Za-z0-9]+', '', text)
  text = re.sub(r'#[A-Za-z0-9]+', '', text)
  text = re.sub(r'RT[\s]+', '', text)
  text = re.sub(r'https?:\/\/\S+', '', text)
  text = re.sub(r'[0-9]', '', text)
  text = re.sub(r'[^\w\s]', '', text)

  text = text.replace('\n', ' ')
  text = text.translate(str.maketrans('', '', string.punctuation))
  text = text.strip(' ')
  return text

def casefoldingText (text):
  text = text.lower()
  return text

def tokenizingText (text):
  text = word_tokenize(text)
  return text

def filteringText (text):
  listStopwords = set(stopwords.words('indonesian'))
  listStopwords1 = set(stopwords.words('english'))
  listStopwords.update(listStopwords1)
  filtered = []
  for txt in text:
      if txt not in listStopwords:
        filtered.append(txt)
  text = filtered
  return text

def stemmingText (text):
  factory = StemmerFactory()
  stemmer = factory.create_stemmer()

  words = text.split()

  stemmed_words = [stemmer.stem(word) for word in words]

  stemmed_text = ' '.join(stemmed_words)

  return stemmed_text

def toSentence(list_words):
  sentence = ' '.join(word for word in list_words)
  return sentence

# Membersihkan teks dan menyimpannya
book_recom_df['Book-Title_clean'] = book_recom_df['Book-Title'].apply(cleaningText)
book_recom_df['Book-Author_clean'] = book_recom_df['Book-Author'].apply(cleaningText)

# Mengubah huruf dalam teks menjadi huruf kecil dan menyimpannya
book_recom_df['Book-Title_clean'] = book_recom_df['Book-Title_clean'].apply(casefoldingText)
book_recom_df['Book-Author_clean'] = book_recom_df['Book-Author_clean'].apply(casefoldingText)

# Memecah teks menjadi token (kata-kata) dan menyimpannya
book_recom_df['Book-Title_clean'] = book_recom_df['Book-Title_clean'].apply(tokenizingText)
book_recom_df['Book-Author_clean'] = book_recom_df['Book-Author_clean'].apply(tokenizingText)


# Menghapus kata-kata stop (kata-kata umum) dan menyimpannya
book_recom_df['Book-Title_filter'] = book_recom_df['Book-Title_clean'].apply(filteringText)

# Menggabungkan token-token menjadi kalimat dan menyimpannya
book_recom_df['Book-Title_sentence'] = book_recom_df['Book-Title_clean'].apply(toSentence)
book_recom_df['Book-Author_sentence'] = book_recom_df['Book-Author_clean'].apply(toSentence)

book_recom_df.head()

"""# Data Preparation 1 (Untuk Content-Based Filtering)"""

book_recom_df.info()

"""## Feature Selection"""

content_df = book_recom_df[['ISBN', 'Book-Title_sentence', 'Book-Author_sentence', 'Year-Of-Publication']]
content_df.head()

content_df.duplicated().sum()

content_df = content_df.drop_duplicates()
content_df.duplicated().sum()

content_df.info()

"""## TF-IDF Vectorizer"""

tfv = TfidfVectorizer()
tfidf_matrix = tfv.fit_transform(content_df['Book-Title_sentence'])
tfidf_matrix.shape

pd.DataFrame(
    tfidf_matrix.toarray(),
    columns=tfv.get_feature_names_out(),
    index=content_df['Book-Author_sentence']
)

"""## One Hot Encode"""

authors = content_df['Book-Author_sentence'].unique()
author_one_hot = pd.get_dummies(content_df['Book-Author_sentence'])
author_one_hot.head()

"""## Normalisasi Tahun"""

minmax = MinMaxScaler()
year_scaled = minmax.fit_transform(content_df[['Year-Of-Publication']])
year_scaled = pd.DataFrame(year_scaled, columns=['Year-Of-Publication'])
year_scaled.head()

"""## Combine Dataset"""

year_sparse = csr_matrix(year_scaled)
combined_features = hstack([tfidf_matrix, author_one_hot, year_sparse])
combined_dense = pd.DataFrame(combined_features.toarray())
combined_dense.head()

"""# Data Preparation 2 (Untuk Collaborative-Filtering)"""

book_recom_df.info()

"""## Feature Selection"""

user_based_df = book_recom_df[['User-ID', 'ISBN', 'Book-Rating']]
user_based_df.info()

user_based_df.isna().sum()

user_based_df.duplicated().sum()

user_based_df['User-ID'] = user_based_df['User-ID'].astype(str)
user_based_df['ISBN'] = user_based_df['ISBN'].astype(str)
user_based_df['Book-Rating'] = user_based_df['Book-Rating'].astype(float)
user_based_df.info()

"""## Encode Feature"""

print(user_based_df['ISBN'].value_counts())

# 1. Ambil list unik User-ID
user_ids = user_based_df['User-ID'].unique().tolist()
print('List User-ID:', user_ids)

# 2. Encoding User-ID (user → index dan sebaliknya)
user_to_user_encoded = {x: i for i, x in enumerate(user_ids)}
user_encoded_to_user = {i: x for i, x in enumerate(user_ids)}

print('Encoded User-ID:', user_to_user_encoded)
print('Encoded index ke User-ID:', user_encoded_to_user)

# 3. Ambil list unik ISBN
isbn_list = user_based_df['ISBN'].unique().tolist()

# 4. Encoding ISBN (isbn → index dan sebaliknya)
isbn_encoded = {x: i for i, x in enumerate(isbn_list)}
isbn_encoded_to_isbn = {i: x for i, x in enumerate(isbn_list)}

# 5. Mapping User-ID dan ISBN ke encoded values
user_based_df['user'] = user_based_df['User-ID'].map(user_to_user_encoded)
user_based_df['book'] = user_based_df['ISBN'].map(isbn_encoded)

# 6. Ubah rating menjadi float32
user_based_df['rating'] = user_based_df['Book-Rating'].astype(np.float32)

# 7. Dapatkan jumlah user & item
num_users = len(user_to_user_encoded)
num_books = len(isbn_encoded_to_isbn)

# 8. Ambil min dan max rating
min_rating = user_based_df['rating'].min()
max_rating = user_based_df['rating'].max()

# 9. Print hasil
print('Number of Users: {}'.format(num_users))
print('Number of Books: {}'.format(num_books))
print('Min Rating: {}'.format(min_rating))
print('Max Rating: {}'.format(max_rating))

user_based_df.head()

"""## Split Data"""

# Mengacak dataset
user_based_df = user_based_df.sample(frac=1, random_state=42)
user_based_df

# Membuat variabel x untuk mencocokkan data user dan resto menjadi satu value
x = user_based_df[['user', 'book']].values

# Membuat variabel y untuk membuat rating dari hasil
y = user_based_df['rating'].apply(lambda x: (x - min_rating) / (max_rating - min_rating)).values

# Membagi menjadi 80% data train dan 20% data validasi
train_indices = int(0.8 * user_based_df.shape[0])
x_train, x_val, y_train, y_val = (
    x[:train_indices],
    x[train_indices:],
    y[:train_indices],
    y[train_indices:]
)

print(x, y)

"""# Modeling 1 Content-Based Filtering

## Hitung Cosine Similarity
"""

cosine_sim = cosine_similarity(combined_dense)
cosine_sim

cosine_df = pd.DataFrame(cosine_sim, index=content_df['Book-Title_sentence'], columns=content_df['Book-Title_sentence'])
cosine_df.head(10)

"""## Rekomendasi"""

def recommend_books_by_isbn(isbn, similarity_data, items, k=5):
    """
    Recommend books based on ISBN using content-based filtering.

    Parameters:
    -----------
    isbn : str
        ISBN of the book to find recommendations for.
    similarity_data : pd.DataFrame
        DataFrame cosine similarity with index and columns = Book-Title_sentence.
    items : pd.DataFrame
        Book data (must contain ISBN, Book-Title_sentence, etc.).
    k : int
        Number of recommendations to return.

    Returns:
    --------
    pd.DataFrame
        Top K recommendations based on content similarity.
    """

    # Ensure ISBN is string
    isbn = str(isbn)

    # Find the index of the book with the given ISBN
    book_index = items[items['ISBN'] == int(isbn)].index

    if book_index.empty:
        print(f"Book with ISBN '{isbn}' not found in the dataset used for similarity.")
        return pd.DataFrame() # Return empty DataFrame if book is not found

    book_index = book_index[0]

    # Get the similarity scores for this book
    similarity_scores = list(enumerate(similarity_data.iloc[book_index]))

    # Sort the books based on the similarity scores in descending order
    sorted_scores = sorted(similarity_scores, key=lambda x: x[1], reverse=True)

    # Get the indices of the top k similar books (excluding the book itself)
    top_k_indices = [i[0] for i in sorted_scores[1:k+1]]

    # Get the recommended books using the indices
    recommended_books = items.iloc[top_k_indices]

    return recommended_books


def get_book_info(isbn, items):
    """
    Get detailed information about a book by ISBN.
    """
    # Ensure ISBN is string for comparison
    isbn = str(isbn)
    # Ensure the 'ISBN' column in items is also string or match the type before comparison
    # Assuming 'ISBN' in items is int based on prior conversion, convert search term to int
    try:
        isbn_int = int(isbn)
    except ValueError:
        return f"Invalid ISBN format: '{isbn}'. ISBN must be a number."

    match = items[items['ISBN'] == isbn_int]
    if match.empty:
        return f"Book with ISBN '{isbn}' not found."

    book = match.iloc[0]
    return {
        'ISBN': book['ISBN'],
        'Title': book['Book-Title_sentence'],
        'Author': book['Book-Author_sentence'],
        'Year': book['Year-Of-Publication']
    }

recommendations = recommend_books_by_isbn(
    isbn='1841721522',
    similarity_data=cosine_df,
    items=content_df,
    k=5
)

if not recommendations.empty:
    print("Recommended Books:")
    display(recommendations)

"""# Modeling 2 Collaborative-Filtering"""

class RecommenderNet(tf.keras.Model):
    def __init__(self, num_users, num_books, embedding_size, **kwargs):
        super(RecommenderNet, self).__init__(**kwargs)
        self.num_users = num_users
        self.num_books = num_books
        self.embedding_size = embedding_size

        # Embedding untuk user
        self.user_embedding = layers.Embedding(
            input_dim=num_users,
            output_dim=embedding_size,
            embeddings_initializer='he_normal',
            embeddings_regularizer=keras.regularizers.l2(1e-6)
        )
        self.user_bias = layers.Embedding(input_dim=num_users, output_dim=1)

        # Embedding untuk buku (dulu resto)
        self.book_embedding = layers.Embedding(
            input_dim=num_books,
            output_dim=embedding_size,
            embeddings_initializer='he_normal',
            embeddings_regularizer=keras.regularizers.l2(1e-6)
        )
        self.book_bias = layers.Embedding(input_dim=num_books, output_dim=1)

    def call(self, inputs):
        user_vector = self.user_embedding(inputs[:, 0])
        user_bias = self.user_bias(inputs[:, 0])
        book_vector = self.book_embedding(inputs[:, 1])
        book_bias = self.book_bias(inputs[:, 1])

        dot_user_book = tf.reduce_sum(user_vector * book_vector, axis=1, keepdims=True)
        x = dot_user_book + user_bias + book_bias

        return tf.nn.sigmoid(x)

embedding_size = 50

model = RecommenderNet(num_users, num_books, embedding_size)
model.compile(
    loss=tf.keras.losses.MeanSquaredError(),
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
    metrics=[tf.keras.metrics.RootMeanSquaredError()]
)

early_stop = EarlyStopping(
    monitor='val_loss',
    patience=5,
    restore_best_weights=True,
    verbose=1
)

model_checkpoint = ModelCheckpoint(
    filepath='best_recommender_model.h5',
    monitor='val_loss',
    save_best_only=True,
    verbose=1
)

reduce_lr = ReduceLROnPlateau(
    monitor='val_loss',
    factor=0.2,
    patience=3,
    min_lr=1e-5,
    verbose=1
)

# Train model with callbacks
history = model.fit(
    x=x_train,
    y=y_train,
    batch_size=16,
    epochs=100,
    validation_data=(x_val, y_val),
    callbacks=[early_stop, model_checkpoint, reduce_lr]
)

"""## Visualization"""

plt.plot(history.history['root_mean_squared_error'], label='Train RMSE')
plt.plot(history.history['val_root_mean_squared_error'], label='Val RMSE')
plt.title('Root Mean Squared Error During Training')
plt.xlabel('Epoch')
plt.ylabel('RMSE')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

"""## Inference"""

# Pastikan kolom User-ID berupa string
user_based_df['User-ID'] = user_based_df['User-ID'].astype(str)
books_df['ISBN'] = books_df['ISBN'].astype(str)

# Pastikan semua key encoding adalah string
user_to_user_encoded = {str(k): v for k, v in user_to_user_encoded.items()}
user_encoded_to_user = {v: k for k, v in user_to_user_encoded.items()}
isbn_encoded = {str(k): v for k, v in isbn_encoded.items()}
isbn_encoded_to_isbn = {v: k for k, v in isbn_encoded.items()}

# 1. Pilih user dari data yang memiliki cukup rating
user_counts = user_based_df['User-ID'].value_counts()
eligible_users = user_counts[user_counts >= 5].index.tolist()
user_id = random.choice(eligible_users)

print(f" Menggunakan user acak: {user_id}")

# 2. Tambahkan user ke encoding jika belum ada
if user_id not in user_to_user_encoded:
    new_id = len(user_to_user_encoded)
    user_to_user_encoded[user_id] = new_id
    user_encoded_to_user[new_id] = user_id

# 3. Mapping kolom user, book, rating untuk user yang dipilih
user_mask = user_based_df['User-ID'] == user_id
user_based_df.loc[user_mask, 'user'] = user_to_user_encoded[user_id]
user_based_df.loc[user_mask, 'book'] = user_based_df.loc[user_mask, 'ISBN'].map(isbn_encoded)
user_based_df.loc[user_mask, 'rating'] = user_based_df.loc[user_mask, 'Book-Rating'].astype(np.float32)

# 4. Jalankan rekomendasi
books_visited_by_user = user_based_df[user_based_df['User-ID'] == user_id]
books_not_visited = books_df[~books_df['ISBN'].isin(books_visited_by_user['ISBN'].values)]['ISBN']
books_not_visited = list(set(books_not_visited).intersection(set(isbn_encoded.keys())))
books_not_visited_encoded = [[isbn_encoded.get(x)] for x in books_not_visited]

if len(books_not_visited_encoded) == 0:
    print(f" Tidak ada buku yang bisa direkomendasikan untuk user {user_id}.")
else:
    user_encoder = user_to_user_encoded.get(user_id)
    user_book_array = np.hstack(
        ([[user_encoder]] * len(books_not_visited_encoded), books_not_visited_encoded)
    )

    # 5. Prediksi rating dan pilih top 10
    ratings = model.predict(user_book_array).flatten()
    top_ratings_indices = ratings.argsort()[-10:][::-1]
    recommended_book_isbns = [
        isbn_encoded_to_isbn.get(books_not_visited_encoded[x][0]) for x in top_ratings_indices
    ]

    # 6. Tampilkan hasil
    print(' Menampilkan rekomendasi untuk User-ID:', user_id)
    print('=' * 50)
    print(' Buku-buku yang disukai user:')
    print('-' * 50)

    # Ambil top 5 buku dengan rating tertinggi dari user
    top_books_user = (
        books_visited_by_user.sort_values(by='rating', ascending=False)
        .head(5)['ISBN'].values
    )

    # DEBUG: Periksa data
    print(" DEBUG INFO:")
    print(f" Top ISBN dari user: {top_books_user}")
    print(f" ISBN rekomendasi: {recommended_book_isbns}")
    print(f" Jumlah buku di books_df: {len(books_df)}")
    print(f" Kolom di books_df: {list(books_df.columns)}")

    # Periksa apakah ISBN ada di books_df
    books_df_match = books_df[books_df['ISBN'].isin(top_books_user)]
    print(f" Buku ditemukan untuk user: {len(books_df_match)}")

    recommended_books_match = books_df[books_df['ISBN'].isin(recommended_book_isbns)]
    print(f" Buku rekomendasi ditemukan: {len(recommended_books_match)}")

    print("\n" + "="*50)

    # Tampilkan buku yang disukai user
    if len(books_df_match) > 0:
        print(" Buku-buku yang disukai user:")
        for idx, row in books_df_match.iterrows():
            # Akses kolom dengan benar
            title = row['Book-Title'] if 'Book-Title' in row else 'Unknown Title'
            author = row['Book-Author'] if 'Book-Author' in row else 'Unknown Author'
            isbn = row['ISBN']

            # Ambil rating dari user untuk buku ini
            user_rating = books_visited_by_user[books_visited_by_user['ISBN'] == isbn]['rating'].iloc[0]

            print(f"    {title}")
            print(f"     {author}")
            print(f"    Rating: {user_rating}")
            print(f"    ISBN: {isbn}")
            print()
    else:
        print(" Tidak ada informasi detail untuk buku yang disukai user.")
        # Coba tampilkan ISBN yang tersedia di books_df
        sample_isbns = books_df['ISBN'].head(10).tolist()
        print(f" Contoh ISBN yang tersedia di books_df: {sample_isbns}")

    print('-' * 50)
    print('✨ Rekomendasi 10 buku teratas:')
    print('-' * 50)

    # Tampilkan rekomendasi
    if len(recommended_books_match) > 0:
        for idx, row in recommended_books_match.iterrows():
            title = row['Book-Title'] if 'Book-Title' in row else 'Unknown Title'
            author = row['Book-Author'] if 'Book-Author' in row else 'Unknown Author'
            isbn = row['ISBN']

            # Ambil predicted rating
            isbn_idx = recommended_book_isbns.index(isbn)
            predicted_rating = ratings[top_ratings_indices[isbn_idx]]

            print(f"    {title}")
            print(f"     {author}")
            print(f"    Predicted Rating: {predicted_rating:.2f}")
            print(f"    ISBN: {isbn}")
            print()
    else:
        print(" Tidak ada informasi detail untuk buku rekomendasi.")
        print(" Kemungkinan masalah:")
        print("   1. ISBN rekomendasi tidak ada di books_df")
        print("   2. Format ISBN tidak sesuai")
        print("   3. Data books_df tidak lengkap")

        # Tampilkan beberapa ISBN untuk debug
        if len(recommended_book_isbns) > 0:
            print(f"    ISBN yang dicari: {recommended_book_isbns[:5]}")

        # Periksa apakah ada ISBN yang mirip
        for isbn in recommended_book_isbns[:3]:
            similar = books_df[books_df['ISBN'].str.contains(isbn[:5], na=False)]
            if len(similar) > 0:
                print(f"    ISBN mirip dengan {isbn}: {similar['ISBN'].iloc[0]}")

# Fungsi tambahan untuk debug
def debug_recommendation_system():
    """
    Fungsi untuk debugging sistem rekomendasi
    """
    print("\n DEBUGGING RECOMMENDATION SYSTEM")
    print("="*50)

    print(" Dataset Info:")
    print(f"   - books_df shape: {books_df.shape}")
    print(f"   - user_based_df shape: {user_based_df.shape}")
    print(f"   - books_df columns: {list(books_df.columns)}")
    print(f"   - user_based_df columns: {list(user_based_df.columns)}")

    print("\n Sample Data:")
    print("books_df sample:")
    print(books_df[['ISBN', 'Book-Title', 'Book-Author']].head(3))

    print("\nuser_based_df sample:")
    print(user_based_df[['User-ID', 'ISBN', 'Book-Rating']].head(3))

    print("\n Encoding Info:")
    print(f"   - Total users encoded: {len(user_to_user_encoded)}")
    print(f"   - Total books encoded: {len(isbn_encoded)}")

    # Periksa konsistensi ISBN
    user_isbns = set(user_based_df['ISBN'].unique())
    book_isbns = set(books_df['ISBN'].unique())
    common_isbns = user_isbns.intersection(book_isbns)

    print(f"\n ISBN Analysis:")
    print(f"   - Unique ISBNs in user_based_df: {len(user_isbns)}")
    print(f"   - Unique ISBNs in books_df: {len(book_isbns)}")
    print(f"   - Common ISBNs: {len(common_isbns)}")
    print(f"   - Missing in books_df: {len(user_isbns - book_isbns)}")

    if len(user_isbns - book_isbns) > 0:
        print(f"   - Sample missing ISBNs: {list(user_isbns - book_isbns)[:5]}")

# Panggil fungsi debug
debug_recommendation_system()

